services:

  back:
    build: ./_build/back
    volumes:
      - ./back:/${APP_NAME}
    working_dir: /${APP_NAME}
    env_file:
      - .env
    environment:
      BUILD_TYPE: "prod"
    restart: "on-failure"
    ports:
      - "4000:4000"
