services:

  nginx:
    build: ./_build/nginx
    depends_on:
      - front
      - back
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./_build/nginx/certs:/certs
    networks:
      - app_network
    restart: "no"

  front:
    build: ./_build/front
    volumes:
      - ./front:/${APP_NAME}
    networks:
      - app_network
    working_dir: /${APP_NAME}
    restart: "no"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"

  back:
    build: ./_build/back
    depends_on:
      - db
    volumes:
      - ./back:/${APP_NAME}
    networks:
      - app_network
    working_dir: /${APP_NAME}
    env_file:
      - .env
    restart: "no"
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"

  db:
    image: mariadb
    volumes:
      - vol_db:/var/lib/mysql/
    networks:
      - app_network
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    restart: "no"

  adminer:
    image: adminer
    depends_on:
      - db
    restart: "no"
    ports:
      - "8081:8080"
    networks:
      - app_network

networks:
  app_network:

volumes:
  vol_db: