services:

  back:
    build: ./_build/back
    volumes:
      - ./back:/${APP_NAME}
    working_dir: /${APP_NAME}
    env_file:
      - .env
    restart: "no"
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
